// w01_lc_hex3_4.js - Data-driven generator for 144 entries
const fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..');
const DF = path.join(ROOT, 'src', 'data', 'lineCategoryInterpretations.data.js');
const NODE = path.join(ROOT, '.nodejs', 'node-v22.14.0-win-x64', 'node.exe');

const C = [
  {i:'general',n:'一般'},{i:'career',n:'工作事業'},{i:'love',n:'感情関係'},
  {i:'money',n:'財務金錢'},{i:'people',n:'人際合作'},{i:'family',n:'家庭親人'},
  {i:'study',n:'學習考試'},{i:'health',n:'身心状態'},{i:'decision',n:'重大決策'},
  {i:'business',n:'創業經營'},{i:'legal',n:'官非合約'},{i:'spiritual',n:'心境修行'}
];
const S = {health:'本欄不做医療診断。',business:'本欄不做獲利保証。',legal:'本欄不做法律結果判定。'};

function E(h,l,c,m,a,w,b) {
  return {
    id:'hex-'+String(h).padStart(3,'0')+'-line-'+l+'-'+c.i, hexagramId:h, line:l,
    category:c.i, categoryName:c.n, meaning:m, advice:a, warning:w+(S[c.i]||''), basis:b,
    scoreAdjust:{clarity:0,action:0,risk:0,change:5,support:0,timing:0},
    qualityLevel:'refined',reviewed:false,needsHumanReview:true,
    version:'1.7.0-v7-summit-w01',reviewedBy:'',reviewedAt:''
  };
}

// Load content data (generated by gen_data.js)
const D = JSON.parse(fs.readFileSync(path.join(__dirname,'w01_data.json'),'utf8'));
const A = [];
for (const d of D) { A.push(E(d.h, d.l, C[d.ci], d.m, d.a, d.w, d.b)); }

// ==== VERIFICATION ====
const F = A.filter(e => e.meaning.length < 90 || e.advice.length < 75 || e.warning.length < 55 || e.basis.length < 4);
if (F.length > 0) {
  console.log('FAIL: ' + F.length + ' entries below thresholds:');
  F.forEach(e => console.log(e.id + ' m=' + e.meaning.length + ' a=' + e.advice.length + ' w=' + e.warning.length + ' b=' + e.basis.length));
  process.exit(1);
}
console.log('ALL ' + A.length + ' entries pass thresholds');

// Uniqueness checks
function norm(t) { return t.replace(/[，。、；：！？\s]/g, ''); }
let dupIssue = false;
for (const c of C) {
  for (const hid of [3,4]) {
    const me = A.filter(e => e.hexagramId === hid && e.category === c.i).map(e => norm(e.meaning));
    if (new Set(me).size !== 6) { console.log('HEX' + hid + ' ' + c.i + ' SAME-CAT not unique'); dupIssue = true; }
  }
}
for (let l = 1; l <= 6; l++) {
  for (const hid of [3,4]) {
    const me = A.filter(e => e.hexagramId === hid && e.line === l).map(e => norm(e.meaning));
    if (new Set(me).size !== 12) { console.log('HEX' + hid + ' L' + l + ' SAME-LINE not unique'); dupIssue = true; }
  }
}
if (!dupIssue) console.log('All uniqueness checks PASS');

// Prohibited phrases
const PROH = ['此為X卦的X爻','結合X卦','起步階段','力量尚未成熟','観察準備','貿然行動','保持彈性','順勢而為','審慎評估','多加溝通','問Y時'];
let probFound = false;
for (const e of A) {
  const t = e.meaning + e.advice + e.warning;
  for (const p of PROH) { if (t.includes(p)) { console.log("PROHIBITED '"+p+"' in "+e.id); probFound = true; } }
}
if (!probFound) console.log('No prohibited phrases found');

// ==== WRITE ====
const vm = require('vm');
global.window = {};
vm.runInThisContext(fs.readFileSync(DF, 'utf8'));
const existing = global.window.Zero1MatrixData.lineCategoryInterpretations;
const idMap = new Map();
for (const e of A) idMap.set(e.id, e);
const updated = [];
let updatedCount = 0;
for (const e of existing) {
  const r = idMap.get(e.id);
  if (r) { updated.push(Object.assign({}, e, r)); updatedCount++; }
  else { updated.push(e); }
}
console.log('Updated ' + updatedCount + ' of ' + existing.length + ' entries');
const out = 'window.Zero1MatrixData = window.Zero1MatrixData || {};\nwindow.Zero1MatrixData.lineCategoryInterpretations = ' + JSON.stringify(updated) + ';';
fs.writeFileSync(DF, out, 'utf8');
console.log('Written to: ' + DF);

// node --check
const {execSync} = require('child_process');
try {
  execSync('"' + NODE + '" --check "' + DF + '"', {encoding:'utf8'});
  console.log('node --check: PASSED');
} catch(err) {
  console.log('node --check: FAILED');
  console.log(err.stderr || err.message);
  process.exit(1);
}
console.log('DONE');